#Playbook for create user Linux

- name: User create 
  hosts: "{{ variable_host | default('localhost') }}"
  
  tasks:

   - debug:
       msg={{ variable_host }}

#Creation group

   - name: Add group to remote server
     group:
       name: nginx
       gid: 220
       state: present

#Creation User

   - name: Add user to remote server
     user:
       name: 
       comment: "App User"
       uid: 222
       group: nginx
       append: yes
       shell: /bin/bash
       password: "{{ 'world' | password_hash('sha512') }}"
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa